### ISSUE TITLE
Endpoint Support

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#109]
- [x] Endpoint trait support
- [x] Basic AWS endpoint implementation
- [x] endpoints.json dynamic resolver generation
- [ ] Design endpoint discovery
- [ ] Endpoint discovery implementation

**Comment by overheat** [comment]
Any workaround for now?
We want to insert records to Timestream using rust SDK.

**Comment by overheat** [comment]
Where to start if I want to implement endpoint discovery?

**Comment by rcoh** [comment]
https://awslabs.github.io/smithy/1.0/spec/aws/aws-core.html#client-endpoint-discovery

We'd probably need some sort of custom middleware stage, I'd probably start with an RFC.

**Comment by jdisanti** [comment]
The work tracked in this issue has been superseded by #1784.
