### ISSUE TITLE
CI improvements superissue

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1102]
### Publisher tool
- [x] Add PR check that SDK has no cyclic dependencies (#1104)
- [x] Add PR sanity check for version numbers (#1104)
- [x] Add `aws-sdk-rust` git repo tag check to `publish` sub-command (#1104)
- [x] Fix publisher tool's yank subcommand to work from smithy-rs (#1104)
- [x] Add `publish = false` to example manifests when copying them into the final build artifacts (#1109)

### Smithy-rs `aws:sdk:assemble`
- [x] Automate updating of versions in README (#1109)
- [x] Automate copying of the SDK changelog to the aws-sdk-rust repo (#1109)

### Sync tool
- [x] Update sync tool to ensure that `next` and `main` stay properly in git-sync (#1115)
  -  Currently, we have to manually reset the `next` branch to be based on the latest commit to `main` after every release
- [x] Investigate the repo sync tool to see if the method it's using to build new versions of the SDK isn't correctly applying the desired versions from `gradle.properties`

### Misc
- [x] Update the changelog formatting tool so it doesn't print a newline if a change category had no changes (included in #1085)
