### ISSUE TITLE
Retries Tracking

### ISSUE THREAD

**Issue by Velfi** [awslabs/smithy-rs#1583]
This issue tracks the improvements we want to make to retries during Q3

- [ ] [[request]: S3 DNS re-lookup on retry](https://github.com/awslabs/aws-sdk-rust/issues/160)
- [ ] [Should ResponseErrors be retriable?](https://github.com/awslabs/aws-sdk-rust/issues/303)
- [ ] [IMDS provider should retry on 401](https://github.com/awslabs/smithy-rs/issues/1156)
- [ ] [Treat sts::IdpCommunicationError as a transient error](https://github.com/awslabs/smithy-rs/issues/966)
- [ ] [Missing sleep impl results in confusion around timeouts and retry](https://github.com/awslabs/aws-sdk-rust/issues/586)

**Comment by jdisanti** [comment]
Closing this tracking issue in favor of #1692.
