### ISSUE TITLE
Migrate to Smithy's `DirectedCodegen` pattern

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1675]
Smithy now provides a [`DirectedCodegen`](https://github.com/awslabs/smithy/blob/main/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java#L35) interface that essentially replaces the need to write a `CodegenVisitor`, and standardizes the patterns that the newer Smithy code generators have established.

I spent some time investigating what it would take to refactor our code generator to use the `DirectedCodegen` approach, and discovered this list of smaller refactors we can do that will make the transition a lot easier:

- [ ] Use `NodeMapper.deserialize` to parse `-RustSettings` instead of manual parsing:
```kotlin
S deserialized = new NodeMapper().deserialize(settingsNode, settingsType);
```
This method of parsing is _required_ to use `DirectedCodegen` since the `CodegenDirector` does the parsing.
- [ ] Replace `OperationNormalizer` with `ModelTransformer.createDedicatedInputAndOutput`
- [ ] Refactor existing codegen to write its file entries into a Smithy `FileManifest`
- [ ] Eliminate direct use of `RustSymbolProvider`; only the `SymbolProvider` interface may be used in codegen

Additionally, we would need to break the Client/Server inheritance model for the `RustSettings` and `CodegenContext` classes since the types for these need to be known at compile time. The best way to do this would probably be to keep them, but they go into their respective client/server modules, and then have a `ClientDirectedCodegen` and a `ServerDirectedCodegen`. Essentially, the server codegen would need to become its own Smithy plugin, and the shared code between client and server would need to go into a core module.

Once all of these refactors are done, it looks like it should be possible to migrate, but it will still be a considerable amount of work.

**Comment by jdisanti** [comment]
Replacing the `OperationNormalizer` is blocked on https://github.com/awslabs/smithy/issues/1373
