### ISSUE TITLE
SDK Production Readiness

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1692]
This is the tracking issue for making the AWS SDK for Rust production ready (but not stable; after production readiness, breaking changes will still be made to the SDK leading up to its GA release). _Note:_ this should give a general sense of the total work remaining, but more tasks may be added if other issues are discovered.

### Retries

- [ ] [[request]: S3 DNS re-lookup on retry](https://github.com/awslabs/aws-sdk-rust/issues/160)
- [ ] [Should ResponseErrors be retriable?](https://github.com/awslabs/aws-sdk-rust/issues/303)
- [ ] #1156
- [ ] #966
- [ ] [Missing sleep impl results in confusion around timeouts and retry](https://github.com/awslabs/aws-sdk-rust/issues/586)

### Timeouts

- [ ] #256 
- [x] #722 
- [ ] #134 
- [x] #723 
- [ ] #1562 
- [ ] aws-sdk-rust#586

### Errors and Debuggability

- [ ] #1345
- [ ] #1568
- [ ] #371

### Testing

- [ ] #1304
- [ ] #1392

### Other

- [ ] #1496
- [ ] #627
- [ ] #764
- [ ] #1112
- [ ] aws-sdk-rust#586
- [ ] #820

**Comment by josh-zozonz** [comment]
Now that all the tasks have been done, is this production-ready?

**Comment by jdisanti** [comment]
We’re still in Developer Preview. This task lists what we think is necessary for safely using the SDK in production, but since we’re in Developer Preview, any use in production is at your own risk. There is currently no production-level support available.

**Comment by RogerSanders** [comment]
First of all, thanks for all the time and effort that's going into this project. I'm sorry to basically re-ask the same question as above in another way, but I'd like a little more clarification. On the main readme at https://github.com/awslabs/aws-sdk-rust, it currently states:

"Please Note: The SDK is currently released as a developer preview and is intended strictly for feedback purposes only. Do not use this SDK for production workloads."

It also refers us to the roadmap for the SDK, which leads to this open issue, which states:
"This is the tracking issue for making the AWS SDK for Rust production ready"
Where all listed items are ticked off... but the issue is still open, indicating it hasn't actually been "signed off" as production ready yet.

I'm making decisions right now about design and architecture for several new major systems. Development will take time, we're ages away from production, and I want to use the AWS rust SDK, but for obvious reasons, it'll be hard to get the sign-off for final release if we reach that point and we're bound to an API that explicitly states "do not use this SDK for production workloads". We're pushing boundaries, being on the bleeding edge is fine. I don't need a "general availability" release, I just need to know whether the AWS Rust API appears to be on schedule to be "blessed" for production workloads between now and our release target. Right now it's not clear to me whether we've basically reached "production ready" and someone just needs to close the issue and update the readme, or whether we're miles away but this issue hasn't been kept up to date about what the current "blockers" are or what actual work remains.

I'm going to play semantics a bit here. For me "production ready" has two meanings. There's the technical question - "Has the system reached a level of stability and completeness where it should in theory be usable in production environments without major issues?". There's also the business question "Is this system being offered with support and technical assistance for use in production environments?". Right now, I only care about the first. Reading between the lines, it seems to me like the API has reached a level of technical maturity where it should be safe and reliable in production, but it is still considered, as you stated, "at your own risk", with "currently no production-level support available." If this is indeed the case, could I please ask that someone modify the readme at https://github.com/awslabs/aws-sdk-rust and tone down the language? That statement was added two years ago, and it seems this API is in quite a different place now. Maybe something like this would be more appropriate at this stage:

"Please Note: The SDK is currently released as a developer preview, without support or assistance for use on production workloads. Any use in production is at your own risk."

That's a warning I can live with. It's one I can sell. It's very, very hard for me to sell that we should even attempt to use an SDK however that explicitly states "Do not use this" in bold typeface, with no clear timeframe on when that position will change.

**Comment by jdisanti** [comment]
The SDK is now generally available and can be safely used in production.
