### ISSUE TITLE
Complete client timeouts with `sdk-default-configuration.json`

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1732]
This issue tracks implementation of handling the `sdk-default-configuration.json` model file for client-side request timeouts.

- [x] Pull in the `sdk-default-configuration.json` file with the rest of the models during releases
- [ ] Add API to select retry mode in `SdkConfig` and service `Config` (needs RFC)
- [ ] Add ability to override timeout config for individual requests (needs RFC)
- [ ] Implement retry mode value resolution logic that occurs at code generation time (multiple/add/override modes that apply to the base config values)
- [ ] Implement "auto mode" for timeout value resolution
- [ ] Verify if `stsRegionalEndpoints` and `s3UsEast1RegionalEndpoints` default configuration values are still relevant after endpoints 2.0, and implement if so
