### ISSUE TITLE
Client re-exports

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1759]
The following types should get re-exported by generated client crates:

- [x] `ByteStream`
- [ ] `SdkBody` (for use with `ByteStream`)
- [ ] `RetryConfig`, `RetryConfigBuilder`, `RetryMode`
- [ ] `TimeoutConfig`, `TimeoutConfigBuilder`
- [x] `AsyncSleep` and `Sleep`

Edit this issue to track more as they come up.
