### ISSUE TITLE
Endpoints 2.0

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy-rs#1784]
The approach for endpoint resolution is being redone to better support the edge cases without customizations. This is the tracking issue for that work.
## implementation work
- [x] Endpoints resolver generator: #2030 
- [x] Integrate endpoints resolver: #2074 
- [x] deprecate aws_smithy_http::Endpoint: #2074
- [ ] remove aws_smithy_http::Endpoint
- [x] deprecate & remove AwsEndpoint
- [x] Add FIPS builtIn
- [x] Add DualStack builtIn
- [ ] finalize RFC and ensure it reflects the actual implementation

## testing:
- [x]  presigned URL canary
- [ ]  canary with force path style
- [ ]  canary with virtual addressing
- [x]  s3 object lambda tests

## native smithy
- [ ] documentation of how native smithy services can codegenerate an endpoint resolver
- [ ] add a default middleware for native smithy services that sets the endpoint on the request
