### ISSUE TITLE
Aws Json 1.1 Tracking Issue

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#20]
Tracking issue for AwsJson 1.1 support

AwsJson1.1 is done when the protocol tests pass for serialization and deserialization

- [x] Support recursive structures (#6)
- [x] Document type support (#31)
- [x] Error deserializer support
