### ISSUE TITLE
0.57 release tracking issue

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#3097]
Tracking issue for release of 0.57 of smithy-rs
- [x]  #3099 (@rcoh)
- [x] #3052 (@rcoh)
- [x] #3093 (@ysaito1001 )
- [x] #3088 (@ysaito1001 )
- [x] #3091 (@ysaito1001)
- [x] #3084  (@rcoh)
- [x] Remove body 04x feature gating of `read_from` methods

Server:
- [x] https://github.com/awslabs/smithy-rs/pull/3104 (@david-perez)
- [x] https://github.com/awslabs/smithy-rs/pull/3095 (@82marbag)

**Comment by david-perez** [comment]
I need to merge https://github.com/awslabs/smithy-rs/pull/3095, but it won't need any changes to runtime crates.

**Comment by david-perez** [comment]
Generated server SDKs re-export `SdkBody` and `ByteStream` in `lib.rs`:

```
pub use ::aws_smithy_types::body::SdkBody;
pub use ::aws_smithy_types::byte_stream::error::Error as ByteStreamError;
pub use ::aws_smithy_types::byte_stream::AggregatedBytes;
pub use ::aws_smithy_types::byte_stream::ByteStream;
pub use ::aws_smithy_types::date_time::Format as DateTimeFormat;
pub use ::aws_smithy_types::error::display::DisplayErrorContext;
pub use ::aws_smithy_types::Blob;
pub use ::aws_smithy_types::DateTime;
```

I guess that we need to expose similarly named feature flags as the ones in #3088 to toggle exposure of the feature-gated methods in `aws-smithy-types`? cc @drganjoo.

**Comment by rcoh** [comment]
probably not critical since we aren't as worried about compatibility and the server is always going to be HTTP. It's more about forward-looking work to support not-Http things, allow a seamless upgrade to http-body = 1, etc.
