### ISSUE TITLE
Scale example code

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#380]
- [ ] README in the example code repo
- [ ] long term structure & plan for example code
- [ ] organize examples by service
- [ ] Should examples be part of the workspace? Should they be their own workspace?
