### ISSUE TITLE
[tracking] Dependency cleanup

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#407]
- [ ] `aws-hyper` should have test-util be an off-by-default feature
- ~~unnecessary serde/serde_derive dependency on XML services where this is unused~~ https://github.com/awslabs/smithy-rs/issues/931
- [ ] CI job to run `cargo tree -d` (check for duplicate versions in tree)
- [ ] CI job to run `cargo udeps`
- ~~change `pin_project` to `pin_project_lite` (removes syn / proc macro dependency)~~ https://github.com/awslabs/smithy-rs/issues/932

**Comment by jdisanti** [comment]
Tracking the CI pieces in https://github.com/awslabs/smithy-rs/issues/929

**Comment by jdisanti** [comment]
Planning to remove aws-hyper. Closing this since it's not tracking anything anymore.
