### ISSUE TITLE
Push smithy-rs to Maven Central

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#421]
- [ ] Mark APIs as @SmithyInternalApi
- [ ] Set up artifact on Maven Central
- [ ] Set up GitHub action to push to maven central on tags
- [ ] Determine credentials management strategy
- [ ] Versioning strategy

**Comment by jnicholls** [comment]
Is there a written procedure for using smithy-rs as a gradle plugin? I don't see the client or server codegen's published to maven central. How does one use smithy-rs in their own project? Thanks in advance @rcoh

**Comment by rcoh** [comment]
Currently folks usually use it as a git submodule I think. I think @crisidev has an example somewhere

**Comment by nated0g** [comment]
Having `smithy-rs` in maven central would significantly reduce the barrier to entry to actually using it

**Comment by demurgos** [comment]
> Currently folks usually use it as a git submodule I think. I think [@crisidev](https://github.com/crisidev) has an example somewhere

For people who may be looking for this, I believe that this message refers to [crisidev/smithy-rs-pokemon-service](https://github.com/crisidev/smithy-rs-pokemon-service).

**Comment by nated0g** [comment]
Seems like this in now being published?

https://central.sonatype.com/search?q=software.amazon.smithy.rust

**Comment by aajtodd** [comment]
Yes, as of last week we started publishing codegen artifacts to maven central. 

In the near-ish future:
* We have a [PR](https://github.com/smithy-lang/smithy-examples/pull/145) opened to `smithy-examples` repo to add a quickstart for Rust. Once merged you'll be able to use smithy CLI to bootstrap an example project `smithy init -t smithy-rust-quickstart`. 
* Will hopefully get additional guides and documentation on the smithy website around the Rust code generator(s).
