### ISSUE TITLE
Documentation Rev2

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy-rs#69]
The docs as they come out of Smithy have a number of shortcomings:
- [ ] They are mostly HTML, which, while technically markdown is very hard to read _in code_
- [ ] They don't respect rustdoc's first-line-is-the-header convention which leads to docs which are either missing headers or have too much in the header
- [ ] The `<code>FooInput</code>` that is used can't use rustdocs links unless we parse that out and reparent it to an actual thing.
- [ ] Since we are renaming `Exception` to `Error`, if we continue to do that, we must also update the docs
- [ ] `Cargo.toml` description field cannot have Markdown in it
- [ ] Rustdoc for Rust 1.53 requires bare links to be surrounded by angle brackets (e.g., `<https://github.com>` rather than `https://github.com`)
- [ ] Generate code examples for operations that have no required args

**Comment by jdisanti** [comment]
Resolving this in favor of #1068.
